---
title: "Cruise Map"
author: "Nicholas Baetge"
date: "2/7/2020"
output: html_document
---
# Intro

This document highlights how the cruise map was rendered. 


```{r include=FALSE}
library(tidyverse)
library(knitr)
library(data.table) 
library(zoo) 
library(oce)  
library(scales)
#for mapping
library(marmap)
library(ggrepel)
library(ocedata)
library(ggmap)
#for odv type plots
library(lubridate)
library(reshape2)
library(MBA)
library(mgcv)
#colors
library(RColorBrewer)


custom_theme <- function () {
  theme_test(base_size=30) %+replace%
    theme(legend.position="top",
          legend.spacing.x = unit(0.5,"cm"),
          legend.background = element_rect(fill = "transparent",colour = NA),
          legend.key = element_rect(fill = "transparent",colour = NA),
          panel.background = element_rect(fill = "transparent",colour = NA),
          plot.background = element_rect(fill = "transparent",colour = NA)) 
}

custom.colors <- c("AT39" = "#377EB8", "AT34" = "#4DAF4A", "AT38" = "#E41A1C", "AT32" = "#FF7F00", "Temperate" = "#A6CEE3", "Subpolar" = "#377EB8", "Subtropical" = "#FB9A99", "GS/Sargasso" = "#E41A1C", "Early Spring" = "#377EB8", "Late Spring" = "#4DAF4A","Early Autumn" = "#E41A1C", "Summer" = "#E41A1C", "Late Autumn" = "#FF7F00", "Gv2_2019" = "#377EB8", "WOA18_MN" = "#4DAF4A", "WOA18_AN" = "#E41A1C")
```


# Import Data

```{r warning = FALSE}
#import the station coordinates for N3 and N4
station.coord <- read_rds("~/Google Drive File Stream/Shared drives/NAAMES_Carlson/DATA/FINAL/MANUSCRIPT_DATA/Export_MS/Output/processed_bf.2.2020.rds") %>% 
  select(Cruise, Station, Latitude, Longitude, degree_bin, Subregion, Season) %>% 
  group_by(Cruise, Station) %>% 
  mutate(mean_lat = mean(Latitude),
         mean_lon = mean(Longitude)) %>% 
  select(Cruise, Season, Station, Subregion, mean_lat, mean_lon,  degree_bin) %>%
  distinct() %>% 
  mutate(degree_bin = round(mean_lat)) %>% 
  filter(Cruise %in% c("AT38", "AT34")) 

lon <-  station.coord$mean_lon
lat <-  station.coord$mean_lat
pts <-  cbind.data.frame(lon, lat)

```

```{r echo = FALSE, results = 'asis'}
kable(station.coord, caption = "NAAMES 3 and 4 Station Coordinates ")
```

# Plot map 

```{r warning = FALSE, message = FALSE, fig.height = 12, fig.width = 14, fig.align = "center", warning = FALSE}
#define center of map
ll_mean = c(mean(pts$lon, na.rm=T), mean(pts$lat, na.rm = T))

#get raster background map data --- need to acquire google maps api
#gkey <- register_google("AIzaSyCwRox9gfIIDtdqnCdKGDwrJFFveEMqYU4", write=T)
ggm = get_map(location = ll_mean,  maptype = "terrain", source = "google", zoom=4, color="color")

#create map
gg = ggmap(ggm) + 
  #adding bin demarcations
  geom_segment(aes(x = -38, xend = -47, y = 39, yend = 39)) +
  geom_segment(aes(x = -38, xend = -47, y = 40, yend = 40)) +
  geom_segment(aes(x = -38, xend = -47, y = 41, yend = 41)) +
  geom_segment(aes(x = -38, xend = -47, y = 42, yend = 42)) +
  geom_segment(aes(x = -38, xend = -47, y = 43, yend = 43)) +
  geom_segment(aes(x = -38, xend = -47, y = 44, yend = 44)) +
  geom_segment(aes(x = -38, xend = -47, y = 45, yend = 45)) +
  geom_segment(aes(x = -38, xend = -47, y = 46, yend = 46)) +
  geom_segment(aes(x = -38, xend = -47, y = 47, yend = 47)) +
  geom_segment(aes(x = -38, xend = -47, y = 48, yend = 48)) +
  geom_segment(aes(x = -38, xend = -47, y = 49, yend = 49)) +
  geom_segment(aes(x = -38, xend = -47, y = 50, yend = 50)) +
  geom_segment(aes(x = -38, xend = -47, y = 51, yend = 51)) +
  geom_segment(aes(x = -38, xend = -47, y = 52, yend = 52)) +
  geom_segment(aes(x = -38, xend = -47, y = 53, yend = 53)) +
  geom_segment(aes(x = -38, xend = -47, y = 54, yend = 54)) +
  geom_segment(aes(x = -38, xend = -47, y = 55, yend = 55)) +
  geom_segment(aes(x = -38, xend = -47, y = 56, yend = 56)) +
  geom_segment(aes(x = -38, xend = -47, y = 57, yend = 57)) +
  geom_segment(aes(x = -38, xend = -38, y = 39, yend = 57)) +
  geom_segment(aes(x = -47, xend = -47, y = 39, yend = 57)) +
  geom_point(data = station.coord, aes(x = mean_lon, y = mean_lat, shape = Season, fill = Subregion), color = " black", size = 8, alpha = 0.7, stroke = 2) +
  scale_fill_manual(values = custom.colors) + 
  scale_shape_manual(values = c(21,22,23,24)) +
  labs(y = expression(italic("Latitude, ˚N")),  x = expression(italic("Longitude, ˚W"))) +
  guides(fill = guide_legend(override.aes = list(shape = 21),
                         nrow = 2, byrow = T, title.position = "top"),
        shape = guide_legend(nrow = 2, byrow = T, title.position = "top")) +
  custom_theme()  +
  theme(legend.key.size = unit(2, 'lines'))

gg
```


```{r}

#saveRDS(gg, file = "~/Google Drive File Stream/Shared Drives/NAAMES_Carlson/DATA/FINAL/MANUSCRIPT_DATA/Export_MS/Figures/Cruise_Map.rds")

#ggsave("Figure1a.jpg", gg, device = "jpg",  width = 14, height = 12, path ="~/Desktop/Export_MS/Submission2/") 
```












